import type { QuestionRule } from "@/knowledge/types";

export const questionRules: QuestionRule[] = [
  {
    id: "rule-antragsverfahren",
    topicId: "unterlagen",
    name: "Einreichung und Unterlagen",
    patterns: ["\\b(einreich|ptoutline|portal)\\b", "\\b(formblatt|unterlagen|anlage)\\b"],
    keywords: ["einreichung", "ptoutline", "portal", "unterlagen", "formblatt", "anlage"],
    synonyme: ["wie reiche ich ein", "wie stelle ich den antrag", "welche unterlagen"],
    answerSlugs: [
      "wie-erfolgt-die-antragseinreichung",
      "seitenumfang-nvf1-antrag",
      "seitenumfang-nvf2-ideenskizze",
      "formblaetter-original",
    ],
    priority: 100,
  },
  {
    id: "rule-antragsrollen",
    topicId: "antragsrollen",
    name: "Antragsrollen und Krankenkassen",
    patterns: ["\\b(antragsberechtigt|antragsteller|beantragen|konsortium|krankenkasse|konsortial)\\b"],
    keywords: ["antragsberechtigt", "antragsteller", "beantragen", "konsortium", "konsortial", "krankenkasse", "beteiligung"],
    synonyme: ["wer darf beantragen", "wer muss beteiligt sein"],
    answerSlugs: [
      "wer-ist-antragsberechtigt",
      "krankenkasse-beteiligung",
      "nachweis-krankenkasse-zweistufig",
    ],
    priority: 110,
  },
  {
    id: "rule-fristen",
    topicId: "fristen",
    name: "Fristen und Laufzeiten",
    patterns: ["\\b(frist|stichtag|deadline|14 tage|laufzeit|48 monate)\\b"],
    keywords: ["frist", "stichtag", "laufzeit", "48", "original", "tage"],
    synonyme: ["bis wann", "wann endet", "wie lange"],
    answerSlugs: ["fristen-originalunterschriften", "projektlaufzeit-maximal"],
    priority: 92,
  },
  {
    id: "rule-zweistufig-konzeptphase",
    topicId: "foerderfaehigkeit",
    name: "Zweistufiges Verfahren und Konzeptphase",
    patterns: ["\\b(zweistufig|ideenskizze|vollantrag|konzeptentwicklungsphase|75000)\\b"],
    keywords: ["zweistufig", "ideenskizze", "vollantrag", "konzeptentwicklungsphase", "75000"],
    synonyme: ["unterschied einstufig zweistufig", "konzeptphase"],
    answerSlugs: ["unterschied-einstufig-zweistufig", "foerderung-konzeptentwicklungsphase"],
    priority: 90,
  },
  {
    id: "rule-datenschutz-it",
    topicId: "formale_voraussetzungen",
    name: "Datenschutz, ePA und TI",
    patterns: ["\\b(datenschutz|dsgvo|epa|telematikinfrastruktur|interoperabilitaet)\\b"],
    keywords: ["datenschutz", "dsgvo", "epa", "telematikinfrastruktur", "interoperabilitaet"],
    synonyme: ["patientendaten", "ti anforderungen"],
    answerSlugs: ["datenschutzvorgaben", "daten-ausserhalb-epa", "ti-und-interoperabilitaet"],
    priority: 88,
  },
  {
    id: "rule-ausschluesse",
    topicId: "foerderfaehigkeit",
    name: "Förderausschlüsse",
    patterns: ["\\b(nicht foerder|ausgeschlossen|ausschlussgruende|formal ausgeschlossen)\\b"],
    keywords: ["nicht", "foerder", "ausgeschlossen", "ausschluss", "formal"],
    synonyme: ["wann wird abgelehnt", "was ist ausgeschlossen"],
    answerSlugs: ["foerderausschluesse", "formale-ausschlussgruende"],
    priority: 86,
  },
  {
    id: "rule-nachweise-und-kosten",
    topicId: "formale_voraussetzungen",
    name: "Nachweise, Verwendungsnachweis und Kosten",
    patterns: ["\\b(verwendungsnachweis|zwischennachweis|infrastrukturpauschale|personalmittel)\\b"],
    keywords: ["verwendungsnachweis", "zwischennachweis", "infrastrukturpauschale", "personalmittel"],
    synonyme: ["abrechnung", "nachweise nach bewilligung"],
    answerSlugs: [
      "nachweise-nach-bewilligung",
      "verwendungsnachweis-logik",
      "infrastrukturpauschale-abrechnung",
    ],
    priority: 84,
  },
  {
    id: "rule-verstetigung",
    topicId: "foerderfaehigkeit",
    name: "Verstetigung und Rechtsgrundlagen",
    patterns: ["\\b(selektivvertrag|140a|modellvorhaben|verstetigung|regelversorgung)\\b"],
    keywords: ["selektivvertrag", "modellvorhaben", "verstetigung", "regelversorgung"],
    synonyme: ["wie geht es in die regelversorgung", "welche rechtsgrundlage"],
    answerSlugs: ["rechtsgrundlagen-verstetigung"],
    priority: 80,
  },
];
