import type { QuestionRule } from "@/knowledge/types";

export const questionRules: QuestionRule[] = [
  {
    id: "rule-antragsberechtigung",
    topicId: "antragsrollen",
    name: "Antragsberechtigung und Konsortium",
    patterns: [
      "\\b(antragsberechtigt|antragsberechtigung|wer darf beantragen)\\b",
      "\\b(konsortium|konsortialpartner|verbundpartner)\\b",
    ],
    keywords: ["antrag", "antragsberechtigt", "konsortium", "partner", "rolle"],
    synonyme: ["wer kann einreichen", "berechtigte antragstellende", "verbund"],
    answerSlugs: ["wer-ist-antragsberechtigt", "rollen-im-konsortium"],
    priority: 100,
  },
  {
    id: "rule-foerderfaehigkeit",
    topicId: "foerderfaehigkeit",
    name: "Foerderfaehigkeit Vorhaben",
    patterns: [
      "\\b(foerderfaehig|foerderfaehigkeit|foerderung)\\b",
      "\\b(innovationsfonds|nvf1|nvf2)\\b",
    ],
    keywords: ["foerderfaehig", "projektidee", "innovationsfonds", "nvf1", "nvf2"],
    synonyme: ["passt unser projekt", "welche vorhaben", "foerderkriterien"],
    answerSlugs: ["wann-ist-ein-vorhaben-foerderfaehig"],
    priority: 95,
  },
  {
    id: "rule-fristen",
    topicId: "fristen",
    name: "Fristen und Stichtage",
    patterns: [
      "\\b(frist|fristen|stichtag|deadline|einreichungsfrist)\\b",
      "\\b(einreichung|abgabe|submission)\\b",
    ],
    keywords: ["frist", "stichtag", "einreichung", "abgabe", "deadline"],
    synonyme: ["bis wann einreichen", "wann endet", "zeitplan einreichung"],
    answerSlugs: ["welche-fristen-gelten-fuer-die-einreichung"],
    priority: 90,
  },
  {
    id: "rule-unterlagen",
    topicId: "unterlagen",
    name: "Pflichtunterlagen",
    patterns: [
      "\\b(unterlagen|dokumente|anlagen|anhang|nachweise)\\b",
      "\\b(formblatt|formular|leitfaden)\\b",
    ],
    keywords: ["unterlagen", "anlagen", "formular", "nachweis", "leitfaden"],
    synonyme: ["was muss eingereicht werden", "welche anlagen", "dokumentenliste"],
    answerSlugs: ["welche-unterlagen-sind-pflicht"],
    priority: 90,
  },
  {
    id: "rule-formalia",
    topicId: "formale_voraussetzungen",
    name: "Formale Anforderungen",
    patterns: [
      "\\b(formal|formale voraussetzungen|zulassigkeit|vorgaben)\\b",
      "\\b(nebenbestimmungen|anbest|auflagen)\\b",
    ],
    keywords: ["formal", "voraussetzungen", "anbest", "auflagen", "compliance"],
    synonyme: ["welche vorgaben gelten", "rechtliche vorgaben", "bewilligungsauflagen"],
    answerSlugs: ["welche-formalen-voraussetzungen-gelten", "welche-nebenbestimmungen-gelten"],
    priority: 85,
  },
  {
    id: "rule-personalmittel",
    topicId: "formale_voraussetzungen",
    name: "Personalmittelsaetze und Kosten",
    patterns: [
      "\\b(personalmittel|personalmittelsaetze|tv-l|personalkosten)\\b",
      "\\b(kostenplan|kalkulation|foerderfaehige kosten)\\b",
    ],
    keywords: ["personalmittel", "tv-l", "personalkosten", "kalkulation", "kostenplan"],
    synonyme: ["personalsaetze", "kostenansatz", "budget personal"],
    answerSlugs: ["wie-werden-personalmittel-angesetzt"],
    priority: 80,
  },
  {
    id: "rule-faq",
    topicId: "unterlagen",
    name: "FAQ-basierte Standardfragen",
    patterns: ["\\b(faq|haeufige fragen|haeufig gestellte fragen)\\b"],
    keywords: ["faq", "fragen", "standardfragen"],
    synonyme: ["allgemeine fragen", "typische fragen"],
    answerSlugs: ["wo-finde-ich-verbindliche-quellen"],
    priority: 70,
  },
  {
    id: "rule-nicht-eindeutig",
    topicId: "foerderfaehigkeit",
    name: "Unscharfe Anfrage",
    patterns: [".*"],
    keywords: ["projekt", "antrag", "innovationsfonds"],
    synonyme: [],
    answerSlugs: ["wie-gehe-ich-bei-unklarer-frage-vor"],
    priority: 1,
  },
];
